name: quote app

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: subhan1011/quote-app-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: subhan1011/quote-app-frontend:latest

  deploy:
    needs: [build-and-push-backend, build-and-push-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ec2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "quote-app-with-docker" ]; then
              git clone https://github.com/Subhan-Ali4/quote-app-with-docker.git
            fi
            cd quote-app-with-docker
            git pull origin main
            docker pull subhan1011/quote-app-backend:latest
            docker pull subhan1011/quote-app-frontend:latest
            docker-compose down
            docker-compose up -d
